# pubmed_retriever
email: ''
ncbi_api_key: ''

pmid_list_path: 'pmid_lists/pmid_list_short.csv'
store_retrieved_articles_path: 'retrieved_articles'
store_retrieved_articles_file_name: 'retrieved_articles'

