# gliner_config.yaml
model_name: "urchade/gliner_large_bio-v0.1"
threshold: 0.2
processing: "document"  # options: document, sentence, label
flat_ner: True         # Whether to perform Flat NER, i.e., no overlapping entities
multi_label: False     # Whether to perform multi-label extraction, i.e., multiple labels for the same entity

#corpus_file_path: "retrieved_articles/vanessa_annotations.txt"
corpus_file_path: "retrieved_articles/retrieved_articles.txt"
output_directory: "predicted_annotations"
include_configuration_in_output: False

has_ground_truth: False

clef_labels: &clef_labels
  OHMI_0000003: "microbiome"
  MESH_D004194: "disease"
  NCBITaxon_2: "bacteria"
  SNOMEDCT_67261001: "gene"
  MESH_68019587: "dietary supplement"
  CHEBI_23888: "drug"
  CHEBI_59999: "chemical"
  CHEBI_25212: "metabolite"
  CHEBI_25512: "neurotransmitter"
  NCIT_C13717: "anatomical location"
  NCBITaxon_9606: "human"
  NCIT_C14182: "animal"
  OBI_0000070: "assay"
  WHYISHERE: "intervention or procedure"

biored_labels: &biored_labels
  T003: "Phenotypic Feature"
  T004: "Chemical"
  T005: "Chemical Entity"
  T006: "Organism"
  T007: "Organism Taxonomy"

medmentions_labels: &medmentions_labelspre
  T103: "Chemical"
  T038: "Biologic Function"
  T017: "Anatomical Structure"
  T007: "Bacterium"
  T031: "Body Substance"
  T204: "Eukaryote"
  T168: "Food"
  T201: "Clinical Attribute"
  T005: "Virus"
  T022: "Body System"

labels: *clef_labels