# gliner_config.yaml
#model_name: "urchade/gliner_large_bio-v0.1"
#model_name: "urchade/gliner_large_bio-v0.2"
#model_name: "kzuri/gliner-bio-finetuned"
#model_name: "knowledgator/gliner-bi-large-v1.0"
model_name: "numind/NuNerZero"
threshold: 0.2
processing: "document"  # options: document, sentence, label
flat_ner: True         # Whether to perform Flat NER, i.e., no overlapping entities
multi_label: False     # Whether to perform multi-label extraction, i.e., multiple labels for the same entity

corpus_file_path: "retrieved_articles/vanessa_annotations.txt"
#corpus_file_path: "retrieved_articles/retrieved_articles.txt"
output_directory: "predicted_entities"
include_configuration_in_output: False

pubtator_aggregated_predictions_file_name: "predicted_entities.txt"
json_aggregated_predictions_file_name: "predicted_entities.json"
pubtator_comparison_ground_truth_predicted_file_name: "predicted_entities_ground_truth_comparison.txt"

has_ground_truth: True

clef_entity_labels: &clef_labels
  OHMI_0000003: "microbiome"
  MESH_D004194: "disease"
  NCBITaxon_2: "bacteria"
  SNOMEDCT_67261001: "gene"
  MESH_68019587: "dietary supplement"
  CHEBI_23888: "drug"
  CHEBI_59999: "chemical"
  CHEBI_25212: "metabolite"
  CHEBI_25512: "neurotransmitter"
  NCIT_C13717: "anatomical location"
  NCBITaxon_9606: "human"
  NCIT_C14182: "animal"
  OBI_0000070: "assay"
  
biored_labels: &biored_labels
  NCIT_C25218: "intervention or procedure"
  T003: "Phenotypic Feature"
  T004: "Chemical"
  T005: "Chemical Entity"
  T006: "Organism"
  T007: "Organism Taxonomy"

medmentions_labels: &medmentions_labelspre
  T103: "Chemical"
  T038: "Biologic Function"
  T017: "Anatomical Structure"
  T007: "Bacterium"
  T031: "Body Substance"
  T204: "Eukaryote"
  T168: "Food"
  T201: "Clinical Attribute"
  T005: "Virus"
  T022: "Body System"

entity_labels: *clef_labels